---
- hosts: all
  become: yes

  tasks:
     
### LAMP SERVER INSTALLATION ###

  - name: install LAMP server
    apt:
      name: mariadb-client,apache2,php,libapache2-mod-php,php-cgi,php-common,php-pear,php-mbstring,php-fpm
      state: latest

### PHP CONFIGURATION ###

  - name: enable php7.3-cgi
    command: a2enconf php7.3-cgi
    
  - name: enable php7.3-fpm
    command: a2enconf php7.3-fpm

  - name: edit /etc/php/7.3/apache2/php.ini
    replace:
      path: /etc/php/7.3/apache2/php.ini
      regexp: ';date.timezone ='
      replace: "date.timezone = 'Europe/Paris'"
           
  - name: restart Apache2 service
    service:
      name: apache2
      state: restarted

