---
- hosts: srv-database-2
  become: yes

  tasks:

### FQDN CONFIGURATION ###

  - name: delete hosts file
    file:
      state: absent
      path: /etc/hosts

  - name: create & config hosts file
    copy:
      dest: /etc/hosts
      content: |
        127.0.0.1       localhost.equipe3.sirt.tp       localhost
        10.10.1.15      srv-proxy-1.equipe3.sirt.tp     srv-proxy-1
        10.10.1.16      srv-proxy-2.equipe3.sirt.tp     srv-proxy-2
        10.10.1.21      srv-web-1.equipe3.sirt.tp       srv-web-1
        10.10.1.22      srv-web-2.equipe3.sirt.tp       srv-web-2
        10.10.1.31      srv-database-1.equipe3.sirt.tp  srv-database-1
        10.10.1.32      srv-database-2.equipe3.sirt.tp  srv-database-2
        10.10.1.33      srv-database-3.equipe3.sirt.tp  srv-database-3
        
        # The following lines are desirable for IPv6 capable hosts
        ::1     localhost ip6-localhost ip6-loopback
        ff02::1 ip6-allnodes
        ff02::2 ip6-allrouters
 
 
 
 ### AUTO EDIT RESOLV.CONF ###
 
  - name: install resolvconf
    apt: 
      name: resolvconf
      state: latest
      
  - name: edit resolv.conf
    blockinfile:
      path: /etc/resolvconf/resolv.conf.d/head
      block: |
        nameserver 10.10.1.2
        nameserver 10.10.1.3
    
   

### MARIADB CONFIGURATION ###

  - name: edit /etc/mysql/mariadb.conf.d/50-server.cnf
    replace:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: 'bind-address'
      replace: '#bind-address'
      
  - name: cluster config
    blockinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      block : |
        [galera]
        wsrep_on=ON
        wsrep_provider=/usr/lib/galera/libgalera_smm.so
        
        binlog_format=ROW
        default_storage_engine=innodb
        innodb_autoinc_lock_mode=2
        bind-address=0.0.0.0
        
        # Galera Cluster Configuration
        wsrep_cluster_name="MariaDB_Cluster"
        wsrep_cluster_address="gcomm://10.10.1.31,10.10.1.32,10.10.1.33"
        wsrep_sst_method=rsync
        
        # Galera Node Configuration
        wsrep_node_address="10.10.1.32"
        wsrep_node_name="srv-database-2"

# Install net-tools / nmap / dos2unix

  - name: Install net-tools / nmap / dos2unix
    apt:
      name: dos2unix,net-tools,nmap
      state: latest

### Reboot the System and trop MySLQ service ###

  - name: reboot srv-database-2
    reboot:
    
  - name: stop mysql service
    service:
      name: mysql
      state: stopped
      enabled: yes