---
- hosts: srv-dns-slave
  become: yes

  tasks:

### NFS CLIENT CONFIGURATION ###

  - name: Install latest version of "nfs-common"
    apt:
      name: nfs-common
      state: latest

  - name: Creates directory
    file:
      path: /share
      state: directory

  - name: Creates directory
    file:
      path: /share/dns_client
      state: directory

  - name: Execute the command
    shell: sudo mount 10.10.1.40:/share/dns/slave  /share/dns_client

  - lineinfile:
      dest: /etc/fstab
      line: '10.10.1.40:/share/dns/slave  /share/dns_client    nfs  _netdev,rw 0 0'

  ### CRON CONFIG ###

  - name: create script
    copy:
      dest: /usr/bin/backup.sh
      content: |
        #!/bin/bash
        cp /etc/hosts /share/dns_client/
        cp /etc/host.conf /share/dns_client/
        cp /etc/resolvconf/resolv.conf.d/head /share/dns_client/
        cp /etc/bind/named.conf.local /share/dns_client/
        cp /etc/bind/named.conf.options /share/dns_client/

  - name: chmod
    shell : chmod 755 /usr/bin/backup.sh

  - name: config cron
    cron:                                                                                          
      minute: "30"
      hour: "19"
      day: "*"
      month: "*"
      weekday: "1,2,3,4,5"
      job: /usr/bin/backup.sh

  - name: restart cron
    shell: /etc/init.d/cron restart

### FQDN CONFIGURATION ###

  - name: delete hosts file
    file:
      state: absent
      path: /etc/hosts
      
  - name: create & config hosts file
    copy:
      dest: /etc/hosts
      content: |
        127.0.0.1       localhost.equipe3.sirt.tp       localhost
        10.10.1.3       srv-dns-slave.equipe3.sirt.tp   srv-dns-slave

        # The following lines are desirable for IPv6 capable hosts
        ::1     localhost ip6-localhost ip6-loopback
        ff02::1 ip6-allnodes
        ff02::2 ip6-allrouters

        
  - name: config /etc/host.conf
    lineinfile:
      path: /etc/host.conf
      line: "order hosts, bind"
      insertbefore: "multi on"
  
    
    
 ### AUTO EDIT RESOLV.CONF ###
 
  - name: install resolvconf
    apt: 
      name: resolvconf
      state: latest
      
  - name: edit resolv.conf
    blockinfile:
      path: /etc/resolvconf/resolv.conf.d/head
      block: |
        nameserver 10.10.1.2
        nameserver 10.10.1.3

# Install net-tools / nmap / dos2unix

  - name: Install net-tools / nmap / dos2unix
    apt:
      name: dos2unix,net-tools,nmap
      state: latest

 ### DNS CONFIGURATION ###

  - name: install bind9
    apt: 
      name: bind9
      state: latest
  
  - name: Install dnsutils
    apt:
      name: dnsutils
      state: latest

  - name: config /etc/bind/named.conf.local
    blockinfile:
      path: /etc/bind/named.conf.local
      block: |
        zone "equipe3.sirt.tp" {
            type slave;
            masters { 10.10.1.2; };
            file "/var/lib/bind/db.equipe3.sirt.tp";
        };
        
        zone "1.10.10.in-addr.arpa" {
            type slave;
            masters { 10.10.1.2; };
            file "/var/lib/bind/db.1.10.10.in-addr.arpa";
        };
        
        
  - name: delete /etc/bind/named.conf.options
    file:
      path: /etc/bind/named.conf.options
      state: absent


  - name: create /etc/bind/named.conf.options
    file:
      path: /etc/bind/named.conf.options
      state: touch
      
      
  - name: config /etc/bind/named.conf.options
    blockinfile:
      path: /etc/bind/named.conf.options
      marker: "// {mark} named.conf.options"
      block: |
        options {
                directory "/var/cache/bind";

                // If there is a firewall between you and nameservers you want
                // to talk to, you may need to fix the firewall to allow multiple
                // ports to talk.  See http://www.kb.cert.org/vuls/id/800113

                // If your ISP provided one or more IP addresses for stable
                // nameservers, you probably want to use them as forwarders.
                // Uncomment the following block, and insert the addresses replacing
                // the all-0's placeholder.

                forwarders {
                        10.10.1.2;
                        10.10.1.3;
                        192.168.4.2;
                        8.8.8.8;
                        8.8.4.4;
                };
                //========================================================================
                // If BIND logs error messages about the root key being expired,
                // you will need to update your keys.  See https://www.isc.org/bind-keys
                //========================================================================
                dnssec-validation auto;
                
                listen-on { 127.0.0.1; 10.10.1.3; 192.168.4.2; };
                recursion no;
                allow-query-cache { none; };
                additional-from-cache no;
                allow-transfer {10.10.1.3; };
                auth-nxdomain no;    # conform to RFC1035
                version none;
                forward only;
                //listen-on-v6 { any; };
        };


### Reboot the System ###

  - name: reboot the virtual machine
    reboot: