---
- hosts: srv-nat
  become: yes
  
  tasks:  
  
### FQDN CONFIGURATION ###

  - name: delete hosts file
    file:
      state: absent
      path: /etc/hosts
      
  - name: create & config hosts file
    copy:
      dest: /etc/hosts
      content: |
        127.0.0.1       localhost.equipe3.sirt.tp   localhost
        10.10.1.99       srv-nat.equipe3.sirt.tp     srv-nat

        # The following lines are desirable for IPv6 capable hosts
        ::1     localhost ip6-localhost ip6-loopback
        ff02::1 ip6-allnodes
        ff02::2 ip6-allrouters
        


### NAT CONFIGURATION ###

  - name: allow ip routing
    lineinfile:
      path: /etc/sysctl.conf
      regexp: '#net.ipv4.ip_forward=1'
      line: 'net.ipv4.ip_forward=1'
      backrefs: yes

  - name: configurate ssh
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '#Port 22'
      line: 'Port 22'
      backrefs: yes

  - name: restart ssh service 
    command: /etc/init.d/ssh restart

  - name: disabled non used service 
    command: update-rc.d -f inetd remove

  - name: create an Iptables Script
    copy:
      dest: /etc/init.d/firewall
      content: |
        #!/bin/sh
        ### BEGIN INIT INFO
        # Provides:          firewall
        # Required-Start:    $local_fs $remote_fs $network $syslog $named
        # Required-Stop:     $local_fs $remote_fs $network $syslog $named
        # Default-Start:     2 3 4 5
        # Default-Stop:      0 1 6
        # Short-Description: firewall
        # Description: iptables rules for NAT routing
        ### END INIT INFO

        # CLEAN TABLES
        iptables -F
        iptables -t nat -F
        iptables -X
        iptables -t nat -X


        # ROUTER config
        iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE
        iptables -t nat -A POSTROUTING -o enp0s8 -j MASQUERADE
        iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
        iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
        iptables -A FORWARD -i enp0s3 -j ACCEPT
        iptables -A FORWARD -i enp0s8 -j ACCEPT
        iptables -A FORWARD -i eth1 -j ACCEPT
        iptables -A FORWARD -i eth0 -j ACCEPT


        # SSH In
        iptables -t filter -A INPUT -p tcp --dport 2222 -j ACCEPT
        iptables -t filter -A INPUT -p tcp --dport 22 -j ACCEPT

        # SSH Out
        iptables -t filter -A OUTPUT -p tcp --dport 2222 -j ACCEPT
        iptables -t filter -A OUTPUT -p tcp --dport 22 -j ACCEPT

        # DNS In/Out
        iptables -t filter -A OUTPUT -p tcp --dport 53 -j ACCEPT
        iptables -t filter -A OUTPUT -p udp --dport 53 -j ACCEPT
        iptables -t filter -A INPUT -p tcp --dport 53 -j ACCEPT
        iptables -t filter -A INPUT -p udp --dport 53 -j ACCEPT

        # HTTP + HTTPS Out
        iptables -t filter -A OUTPUT -p tcp --dport 80 -j ACCEPT
        iptables -t filter -A OUTPUT -p tcp --dport 443 -j ACCEPT

        # HTTP + HTTPS In
        iptables -t filter -A PREROUTING -p tcp --dport 80 -j DNAT --to 10.10.1.20

        # Mail SMTP:25
        iptables -t filter -A PREROUTING -p tcp --dport 25 -j DNAT --to 10.10.1.10
        iptables -t filter -A OUTPUT -p tcp --dport 25 -j ACCEPT

        # Mail IMAP:143
        iptables -t filter -A PREROUTING -p tcp --dport 143 -j DNAT --to 10.10.1.10
        iptables -t filter -A OUTPUT -p tcp --dport 143 -j ACCEPT


  - name: chmod firewall script
    command: chmod +x /etc/init.d/firewall
    
    
  - name: update rc cache
    command: update-rc.d firewall defaults
    
  # Install net-tools / nmap / dos2unix

  - name: Install net-tools / nmap / dos2unix
    apt:
      name: dos2unix,net-tools,nmap
      state: latest
       
# Reboot the System ###

  - name: reboot srv-nat
    reboot:
